namespace project;

partial class MainForm
{
    private System.ComponentModel.IContainer? components;
    private Panel topPanel;
    private Label ipLabel;
    private TextBox ipAddressTextBox;
    private Label portLabel;
    private TextBox portTextBox;
    private Button startServerButton;
    private Button connectButton;
    private Button disconnectButton;
    private Button newGameButton;
    private Panel contentPanel;
    private TableLayoutPanel boardPanel;
    private Panel rightPanel;
    private Label currentPlayerLabel;
    private Label localPlayerLabel;
    private Label connectionStatusLabel;
    private Label gameStateLabel;
    private ListBox messagesListBox;
    private Label messagesLabel;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        topPanel = new Panel();
        ipLabel = new Label();
        ipAddressTextBox = new TextBox();
        portLabel = new Label();
        portTextBox = new TextBox();
        startServerButton = new Button();
        connectButton = new Button();
        disconnectButton = new Button();
        newGameButton = new Button();
        contentPanel = new Panel();
        boardPanel = new TableLayoutPanel();
        rightPanel = new Panel();
        currentPlayerLabel = new Label();
        localPlayerLabel = new Label();
        connectionStatusLabel = new Label();
        gameStateLabel = new Label();
        messagesListBox = new ListBox();
        messagesLabel = new Label();
        topPanel.SuspendLayout();
        contentPanel.SuspendLayout();
        rightPanel.SuspendLayout();
        SuspendLayout();
        topPanel.Controls.Add(newGameButton);
        topPanel.Controls.Add(disconnectButton);
        topPanel.Controls.Add(connectButton);
        topPanel.Controls.Add(startServerButton);
        topPanel.Controls.Add(portTextBox);
        topPanel.Controls.Add(portLabel);
        topPanel.Controls.Add(ipAddressTextBox);
        topPanel.Controls.Add(ipLabel);
        topPanel.Dock = DockStyle.Top;
        topPanel.Location = new Point(0, 0);
        topPanel.Name = "topPanel";
        topPanel.Size = new Size(1000, 60);
        topPanel.TabIndex = 0;
        ipLabel.AutoSize = true;
        ipLabel.Location = new Point(12, 22);
        ipLabel.Name = "ipLabel";
        ipLabel.Size = new Size(74, 15);
        ipLabel.TabIndex = 0;
        ipLabel.Text = "IP-адрес:";
        ipAddressTextBox.Location = new Point(92, 19);
        ipAddressTextBox.Name = "ipAddressTextBox";
        ipAddressTextBox.Size = new Size(130, 23);
        ipAddressTextBox.TabIndex = 1;
        portLabel.AutoSize = true;
        portLabel.Location = new Point(236, 22);
        portLabel.Name = "portLabel";
        portLabel.Size = new Size(42, 15);
        portLabel.TabIndex = 2;
        portLabel.Text = "Порт:";
        portTextBox.Location = new Point(284, 19);
        portTextBox.Name = "portTextBox";
        portTextBox.Size = new Size(70, 23);
        portTextBox.TabIndex = 3;
        startServerButton.Location = new Point(371, 17);
        startServerButton.Name = "startServerButton";
        startServerButton.Size = new Size(115, 27);
        startServerButton.TabIndex = 4;
        startServerButton.Text = "Создать сервер";
        startServerButton.UseVisualStyleBackColor = true;
        startServerButton.Click += startServerButton_Click;
        connectButton.Location = new Point(492, 17);
        connectButton.Name = "connectButton";
        connectButton.Size = new Size(108, 27);
        connectButton.TabIndex = 5;
        connectButton.Text = "Подключиться";
        connectButton.UseVisualStyleBackColor = true;
        connectButton.Click += connectButton_Click;
        disconnectButton.Enabled = false;
        disconnectButton.Location = new Point(606, 17);
        disconnectButton.Name = "disconnectButton";
        disconnectButton.Size = new Size(96, 27);
        disconnectButton.TabIndex = 6;
        disconnectButton.Text = "Отключиться";
        disconnectButton.UseVisualStyleBackColor = true;
        disconnectButton.Click += disconnectButton_Click;
        newGameButton.Location = new Point(708, 17);
        newGameButton.Name = "newGameButton";
        newGameButton.Size = new Size(93, 27);
        newGameButton.TabIndex = 7;
        newGameButton.Text = "Новая игра";
        newGameButton.UseVisualStyleBackColor = true;
        newGameButton.Click += newGameButton_Click;
        contentPanel.Controls.Add(boardPanel);
        contentPanel.Controls.Add(rightPanel);
        contentPanel.Dock = DockStyle.Fill;
        contentPanel.Location = new Point(0, 60);
        contentPanel.Name = "contentPanel";
        contentPanel.Size = new Size(1000, 640);
        contentPanel.TabIndex = 1;
        boardPanel.CellBorderStyle = TableLayoutPanelCellBorderStyle.Single;
        boardPanel.ColumnCount = 8;
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 12.5F));
        boardPanel.Location = new Point(12, 12);
        boardPanel.Name = "boardPanel";
        boardPanel.RowCount = 8;
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 12.5F));
        boardPanel.Size = new Size(620, 620);
        boardPanel.TabIndex = 0;
        rightPanel.Controls.Add(messagesListBox);
        rightPanel.Controls.Add(messagesLabel);
        rightPanel.Controls.Add(gameStateLabel);
        rightPanel.Controls.Add(connectionStatusLabel);
        rightPanel.Controls.Add(localPlayerLabel);
        rightPanel.Controls.Add(currentPlayerLabel);
        rightPanel.Dock = DockStyle.Right;
        rightPanel.Location = new Point(648, 0);
        rightPanel.Name = "rightPanel";
        rightPanel.Size = new Size(352, 640);
        rightPanel.TabIndex = 1;
        currentPlayerLabel.AutoSize = true;
        currentPlayerLabel.Location = new Point(14, 19);
        currentPlayerLabel.Name = "currentPlayerLabel";
        currentPlayerLabel.Size = new Size(147, 15);
        currentPlayerLabel.TabIndex = 0;
        currentPlayerLabel.Text = "Текущий игрок: Белые";
        localPlayerLabel.AutoSize = true;
        localPlayerLabel.Location = new Point(14, 47);
        localPlayerLabel.Name = "localPlayerLabel";
        localPlayerLabel.Size = new Size(147, 15);
        localPlayerLabel.TabIndex = 1;
        localPlayerLabel.Text = "Ваш цвет: не назначен";
        connectionStatusLabel.AutoSize = true;
        connectionStatusLabel.Location = new Point(14, 75);
        connectionStatusLabel.Name = "connectionStatusLabel";
        connectionStatusLabel.Size = new Size(166, 15);
        connectionStatusLabel.TabIndex = 2;
        connectionStatusLabel.Text = "Состояние: не подключено";
        gameStateLabel.AutoSize = true;
        gameStateLabel.Location = new Point(14, 103);
        gameStateLabel.Name = "gameStateLabel";
        gameStateLabel.Size = new Size(132, 15);
        gameStateLabel.TabIndex = 3;
        gameStateLabel.Text = "Состояние игры: старт";
        messagesListBox.FormattingEnabled = true;
        messagesListBox.ItemHeight = 15;
        messagesListBox.Location = new Point(14, 151);
        messagesListBox.Name = "messagesListBox";
        messagesListBox.Size = new Size(325, 469);
        messagesListBox.TabIndex = 5;
        messagesLabel.AutoSize = true;
        messagesLabel.Location = new Point(14, 128);
        messagesLabel.Name = "messagesLabel";
        messagesLabel.Size = new Size(78, 15);
        messagesLabel.TabIndex = 4;
        messagesLabel.Text = "Сообщения:";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1000, 700);
        Controls.Add(contentPanel);
        Controls.Add(topPanel);
        MinimumSize = new Size(1016, 739);
        Name = "MainForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Шашки по сети";
        topPanel.ResumeLayout(false);
        topPanel.PerformLayout();
        contentPanel.ResumeLayout(false);
        rightPanel.ResumeLayout(false);
        rightPanel.PerformLayout();
        ResumeLayout(false);
    }
}

